version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: fiber_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d fiber_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: go_fiber_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: fiber_db
      DB_PORT: 5432
      DB_SSLMODE: disable
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
